// <auto-generated />
using System;
using Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructura.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251018002127_AddMotivosTipo")]
    partial class AddMotivosTipo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Entidades.CambioEstado", b =>
                {
                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ambito")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreEstado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaHoraFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("SismografoIdentificacionSismografo")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FechaHoraInicio", "Ambito", "NombreEstado");

                    b.HasIndex("SismografoIdentificacionSismografo");

                    b.HasIndex("Ambito", "NombreEstado");

                    b.ToTable("CambioEstados", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Empleado", b =>
                {
                    b.Property<string>("Mail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Mail");

                    b.ToTable("Empleados", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.EstacionSismologica", b =>
                {
                    b.Property<string>("CodigoEstacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DocumentoCertificacionAdquirida")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaSolicitudCertificacion")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NroCertificacionAdquisicion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CodigoEstacion");

                    b.ToTable("EstacionesSismologica", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Estado", b =>
                {
                    b.Property<string>("Ambito")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreEstado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Ambito", "NombreEstado");

                    b.ToTable("Estados", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.MotivoFueraServicio", b =>
                {
                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CambioEstadoAmbito")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CambioEstadoFechaHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("CambioEstadoNombreEstado")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TipoMotivo");

                    b.HasKey("Comentario");

                    b.HasIndex("CambioEstadoFechaHoraInicio", "CambioEstadoAmbito", "CambioEstadoNombreEstado");

                    b.ToTable("MotivosFueraServicio", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.MotivoTipo", b =>
                {
                    b.Property<string>("TipoMotivo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TipoMotivo");

                    b.ToTable("MotivosTipo", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.OrdenDeInspeccion", b =>
                {
                    b.Property<int>("NroOrden")
                        .HasColumnType("int");

                    b.Property<string>("Ambito")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoEstacion")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaHoraCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaHoraFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEstado")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ObservacionCierre")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("NroOrden");

                    b.HasIndex("CodigoEstacion");

                    b.HasIndex("Ambito", "NombreEstado");

                    b.ToTable("OrdenesDeInspeccion", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Rol", b =>
                {
                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmpleadoMail")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Nombre");

                    b.HasIndex("EmpleadoMail");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Sesion", b =>
                {
                    b.Property<DateTime>("FechaHoraDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaHoraHasta")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuarioNombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FechaHoraDesde");

                    b.HasIndex("UsuarioNombreUsuario");

                    b.ToTable("Sesiones", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Sismografo", b =>
                {
                    b.Property<string>("IdentificacionSismografo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ambito")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstacionSismologicaCodigoEstacion")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaAdquisicion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEstado")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NroSerie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdentificacionSismografo");

                    b.HasIndex("EstacionSismologicaCodigoEstacion");

                    b.HasIndex("Ambito", "NombreEstado");

                    b.ToTable("Sismografos", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Usuario", b =>
                {
                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmpleadoMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("NombreUsuario");

                    b.HasIndex("EmpleadoMail");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.CambioEstado", b =>
                {
                    b.HasOne("Dominio.Entidades.Sismografo", null)
                        .WithMany("CambiosEstado")
                        .HasForeignKey("SismografoIdentificacionSismografo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dominio.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("Ambito", "NombreEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Dominio.Entidades.MotivoFueraServicio", b =>
                {
                    b.HasOne("Dominio.Entidades.CambioEstado", null)
                        .WithMany("MotivosFueraServicio")
                        .HasForeignKey("CambioEstadoFechaHoraInicio", "CambioEstadoAmbito", "CambioEstadoNombreEstado")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dominio.Entidades.OrdenDeInspeccion", b =>
                {
                    b.HasOne("Dominio.Entidades.EstacionSismologica", "Estacion")
                        .WithMany()
                        .HasForeignKey("CodigoEstacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dominio.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("Ambito", "NombreEstado")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Estacion");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Dominio.Entidades.Rol", b =>
                {
                    b.HasOne("Dominio.Entidades.Empleado", null)
                        .WithMany("Roles")
                        .HasForeignKey("EmpleadoMail")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dominio.Entidades.Sesion", b =>
                {
                    b.HasOne("Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioNombreUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Dominio.Entidades.Sismografo", b =>
                {
                    b.HasOne("Dominio.Entidades.EstacionSismologica", null)
                        .WithMany("Sismografos")
                        .HasForeignKey("EstacionSismologicaCodigoEstacion")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dominio.Entidades.Estado", "EstadoActual")
                        .WithMany()
                        .HasForeignKey("Ambito", "NombreEstado")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EstadoActual");
                });

            modelBuilder.Entity("Dominio.Entidades.Usuario", b =>
                {
                    b.HasOne("Dominio.Entidades.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoMail")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Dominio.Entidades.CambioEstado", b =>
                {
                    b.Navigation("MotivosFueraServicio");
                });

            modelBuilder.Entity("Dominio.Entidades.Empleado", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Dominio.Entidades.EstacionSismologica", b =>
                {
                    b.Navigation("Sismografos");
                });

            modelBuilder.Entity("Dominio.Entidades.Sismografo", b =>
                {
                    b.Navigation("CambiosEstado");
                });
#pragma warning restore 612, 618
        }
    }
}
